spring:
  profiles:
    group:
      prod:
        - prod
        - common
      dev:
        - dev
        - common
      local:
        - local
        - common
    default: local
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - file:./config/prod/aoo-config.yml
---
spring:
  config:
    activate:
      on-profile: dev
    import: file:./config/dev/aoo-config.yml
---
spring:
  config:
    activate:
      on-profile: local
    import: classpath:aoo-config.yml
---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: aoo-backend
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: com.hoo.aoo.aar.adapter.out.persistence.config.HibernateCustomNamingStrategy
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${database.mysql.username}
    password: ${database.mysql.password}
    url: jdbc:${database.mysql.name}://${database.mysql.address}:${database.mysql.port}/${database.mysql.scheme}?serverTimezone=${database.mysql.timezone}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${security.oauth2.kakao.client-id}
            client-secret: ${security.oauth2.kakao.client-secret}
            authorization-grant-type: ${security.oauth2.kakao.authorization-grant-type}
            redirect-uri: ${security.oauth2.kakao.redirect-uri}
            client-name: kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id